Sample query function
SRJPE/grunID pull request #109
Opened 2023-10-04 19:07 UTC by liz-fw

@ergz this PR creates a function to get samples by season and has three options for datasets (clean, raw, and unprocessed). Also creates a tab in the shiny

2023-10-05 21:08 UTC, ergz requested changes

2023-10-05 21:08 UTC, ergz commented on R/get-sample.R
> +  if(!dataset %in% c("raw", "clean", "unprocessed")) {
you can use `match.arg` for this since you are providing a vector if choices in the function args, see definition of `update_enum_value` for usage

2023-10-31 23:18 UTC, liz-fw commented
@ergz I added the `failed` filter and also fixed the assignment for when both assays failed - should be good to review again!

2023-11-03 17:51 UTC, ergz commented
@liz-fw can you resolve the merge conflict, looks nearly done after that!

2023-11-03 22:35 UTC, ergz approved these changes
looks good!

2023-11-06 16:06 UTC, merged