Issue 41 subsample fn
SRJPE/grunID pull request #134
Opened 2023-12-06 22:11 UTC by liz-fw

you can test this function by running the code:

`subsamples <- generate_subsample(con, 2024)`

I tried to document the logic as well as I could but let me know if you want to walk through it together to confirm it's working as expected. Logic is here: https://docs.google.com/document/d/1aNT4vqLWFA_4bNRnO9ZemTOTR9L3fyCe/edit

2023-12-06 22:56 UTC, ergz commented on R/generate_subsample.R
> +  dplyr::mutate(no_samples = count(location_code, sample_number),
error here, I think maybe missing a `|>` ?

2023-12-06 22:58 UTC, ergz requested changes
I get an error trying to run the function 

```
Error in generate_subsample(con, 2024) : object 'location_code' not found
```

2023-12-07 00:04 UTC, liz-fw commented
@ergz those were lines of code i was testing out but we didn't need! should be working now

2023-12-07 00:27 UTC, ergz commented on R/generate_subsample.R
> +  samples <- grunID::filter_dataset(con, season) |>
now that `grunID::filter_dataset` is being used in more places in the code base we should rename it to something more specific like `sample_filter_to_season` or something like that, just to make it clear what it returns

2023-12-07 00:28 UTC, ergz commented on R/generate_subsample.R
> +    dplyr::add_count(location_code, sample_event_number, name = "no_samples") |>
Instead of `name = "no_samples"` I would use `name = "total_samples_in_event"`

2023-12-07 06:49 UTC, ergz approved these changes
good stuff! I learned about `group_split` and `add_count` now 😄. Logic makes sense, some nip pick stuff for if you have time

1. generate user friendly error when season is not valid
2. after generating subsample produce a summary, I am thinking like what events were sampled 100% and which were chosen at random. This can be a new "feature" issue

2023-12-07 17:01 UTC, merged